steps:
- id: "Run Unit Tests"
  name: 'gcr.io/${PROJECT_ID}/pytest_3'
  args: [ '-v', 'tests/unit/' ]

# TODO: Rebuild this image + use pytest extension to retry on failure to mitigate flaky tests
- id: "Run Integration Tests"
  name: 'gcr.io/${PROJECT_ID}/pytest_3'
  args: [ '-v', 'tests/integration/', '--oid', '${_OID}', '--key', '${_KEY}' ]

- id: "Login to DockerHub"
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']

- id: "Build Docker Image"
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -f ./Dockerfile -t refractionpoint/limacharlie:latest .']

- id: "Push Image to Docker Hub"
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push refractionpoint/limacharlie:latest']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/DOCKERHUB/versions/latest
    env: 'PASSWORD'
  - versionName: projects/${PROJECT_ID}/secrets/DOCKERHUB_USERNAME/versions/latest
    env: 'USERNAME'
