steps:
- name: 'gcr.io/${PROJECT_ID}/pytest_3'
  args: [ '-v', '-rP', 'tests', '--oid', '${_OID}', '--key', '${_KEY}' ]
- name: 'gcr.io/${PROJECT_ID}/pytest_2'
  args: [ '-v', '-rP', 'tests', '--oid', '${_OID}', '--key', '${_KEY}' ]