steps:
- id: "Run Unit Tests"
  name: 'gcr.io/${PROJECT_ID}/pytest_3'
  args: [ '-v', 'tests/unit/' ]

- id: "Run Integration Tests"
  name: 'gcr.io/${PROJECT_ID}/pytest_3'
  args: [ '-v', 'tests/integration/', '--oid', '${_OID}', '--key', '${_KEY}' ]