"""False positive rule commands for LimaCharlie CLI v2."""

from __future__ import annotations

from ._hive_shortcut import make_hive_group
from ..discovery import register_explain

group = make_hive_group("fp", "fp", "false positive rule", "false positive rules")

# Override the generic hive explains with FP-specific documentation.

register_explain("fp.list", """\
List all false positive rules in the organization.  FP rules filter
out detections generated by the 'report' action of D&R rules.  They
apply globally across all rule namespaces and targets.

Each returned record has the same structure as a D&R detection
component but operates on the content of a detection rather than a
raw event.  The originating event is accessible at the 'detect/' path
prefix.
""")

register_explain("fp.get", """\
Get a specific false positive rule by key.  Returns the rule's
detection-like structure and metadata (enabled, expiry, tags).

The rule body uses the same operator syntax as D&R detect components
(is, contains, starts with, ends with, matches, and, or, etc.) but
operates against the detection object, not the raw event.  Access the
original event fields via the 'detect/' path prefix.
""")

register_explain("fp.set", """\
Create or update a false positive rule.  FP rules suppress detections
generated by D&R rules before they reach outputs or the detections
page.  They apply globally across all namespaces and targets.

An FP rule uses the same operator syntax as a D&R detection component
but matches against the detection content rather than the raw event.
The originating event is accessible at the 'detect/' path prefix.

Suppress a specific detection by name:

  op: is
  path: cat
  value: my-detect-name

Ignore detections for a specific file name:

  op: ends with
  path: detect/event/FILE_PATH
  value: this_is_fine.exe

Ignore detections from a specific host:

  op: is
  path: routing/hostname
  value: web-server-2

Combine conditions with boolean logic:

  op: and
  rules:
    - op: is
      path: cat
      value: suspicious-process
    - op: ends with
      path: detect/event/FILE_PATH
      value: known-good.exe

You can set an expiry in usr_mtd to create temporary FP rules (e.g.,
during a maintenance window).

Provide data via --input-file (YAML/JSON) or pipe through stdin.

Examples:
  limacharlie fp set --key ignore-known-good --input-file fp-rule.yaml
  cat fp.json | limacharlie fp set --key temp-suppress
""")

register_explain("fp.delete", """\
Delete a false positive rule by key.  Detections previously suppressed
by this rule will start appearing again.  Requires --confirm for safety.

Examples:
  limacharlie fp delete --key ignore-known-good --confirm
""")
